Repository AY2223S1-CS2113-W12-3/tp, pull requests merged in 2022-10, with the labels that each got.

#20 Fix bug in Parser
  src/main/java/seedu/duke/Parser.java
Labels: priority.High, type.Bug, severity.High

#46 Branch zhou 2
  .gitignore
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/biometrics/Biometrics.java
  src/main/java/seedu/duke/biometrics/WeightAndFat.java
  src/main/java/seedu/duke/biometrics/WeightAndFatList.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/GreetCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/LoadCommand.java
  src/main/java/seedu/duke/command/MarkCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/RemoveExerciseCommand.java
  src/main/java/seedu/duke/command/SaveCommand.java
  src/main/java/seedu/duke/command/SetCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/storage/LoadData.java
  src/main/java/seedu/duke/storage/SaveData.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/biometrics/BiometricsTest.java
  src/test/java/seedu/duke/biometrics/WeightAndFatListTest.java
  src/test/java/seedu/duke/biometrics/WeightAndFatTest.java
  src/test/java/seedu/duke/command/MarkCommandTest.java
  src/test/java/seedu/duke/command/RemoveCommandTest.java
  src/test/java/seedu/duke/command/SetCommandTest.java
  src/test/java/seedu/duke/exercise/ExerciseListTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Enhancement

#61 Add StrengthExercise UML to Developer guide
  docs/DeveloperGuide.md
  docs/UmlDiagrams/StrengthExercise.png
  docs/UmlDiagrams/StrengthExercise.puml
  src/main/java/seedu/duke/exercise/ExerciseList.java
Labels: type.Task

#71 update user guide and developer guide
  docs/DeveloperGuide.md
  docs/UmlDiagrams/Add.png
  docs/UmlDiagrams/Add.puml
  docs/UmlDiagrams/AddWeightAndFat.png
  docs/UmlDiagrams/AddWeightAndFat.puml
  docs/UserGuide.md
Labels: priority.Medium, type.Task
